/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\oJavaOpen\\MyBlog2\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-50d77608",
    path: "/api/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50d77608").then(next)
    },
  },
  {
    name: "v-f0f4222c",
    path: "/guide/2.JAVA%E5%9F%BA%E7%A1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f0f4222c").then(next)
    },
  },
  {
    path: "/guide/2.JAVA基础.html",
    redirect: "/guide/2.JAVA%E5%9F%BA%E7%A1%80.html"
  },
  {
    path: "/guide/2.JAVA基础.html",
    redirect: "/guide/2.JAVA%E5%9F%BA%E7%A1%80.html"
  },
  {
    name: "v-659794af",
    path: "/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-659794af").then(next)
    },
  },
  {
    path: "/faq/index.html",
    redirect: "/faq/"
  },
  {
    name: "v-2a392840",
    path: "/guide/1.%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a392840").then(next)
    },
  },
  {
    path: "/guide/1.数据结构.html",
    redirect: "/guide/1.%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html"
  },
  {
    path: "/guide/1.数据结构.html",
    redirect: "/guide/1.%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html"
  },
  {
    name: "v-3b470644",
    path: "/api/cli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b470644").then(next)
    },
  },
  {
    name: "v-2735121a",
    path: "/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2735121a").then(next)
    },
  },
  {
    path: "/config/index.html",
    redirect: "/config/"
  },
  {
    name: "v-9f30fe6a",
    path: "/guide/3.%20%E9%9B%86%E5%90%88%E9%9D%A2%E8%AF%95%E6%80%BB%E9%9B%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9f30fe6a").then(next)
    },
  },
  {
    path: "/guide/3. 集合面试总集.html",
    redirect: "/guide/3.%20%E9%9B%86%E5%90%88%E9%9D%A2%E8%AF%95%E6%80%BB%E9%9B%86.html"
  },
  {
    path: "/guide/3. 集合面试总集.html",
    redirect: "/guide/3.%20%E9%9B%86%E5%90%88%E9%9D%A2%E8%AF%95%E6%80%BB%E9%9B%86.html"
  },
  {
    name: "v-a67bc284",
    path: "/guide/6.Redis.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a67bc284").then(next)
    },
  },
  {
    name: "v-75b2c75c",
    path: "/guide/Java%E5%85%AB%E8%82%A1%E5%9F%BA%E7%A1%80%EF%BC%88%E5%85%A8%EF%BC%89.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75b2c75c").then(next)
    },
  },
  {
    path: "/guide/Java八股基础（全）.html",
    redirect: "/guide/Java%E5%85%AB%E8%82%A1%E5%9F%BA%E7%A1%80%EF%BC%88%E5%85%A8%EF%BC%89.html"
  },
  {
    path: "/guide/Java八股基础（全）.html",
    redirect: "/guide/Java%E5%85%AB%E8%82%A1%E5%9F%BA%E7%A1%80%EF%BC%88%E5%85%A8%EF%BC%89.html"
  },
  {
    name: "v-7b2baf4c",
    path: "/guide/5.%E5%A4%9A%E7%BA%BF%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b2baf4c").then(next)
    },
  },
  {
    path: "/guide/5.多线程.html",
    redirect: "/guide/5.%E5%A4%9A%E7%BA%BF%E7%A8%8B.html"
  },
  {
    path: "/guide/5.多线程.html",
    redirect: "/guide/5.%E5%A4%9A%E7%BA%BF%E7%A8%8B.html"
  },
  {
    name: "v-4e0e481e",
    path: "/guide/4.MySQL.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e0e481e").then(next)
    },
  },
  {
    name: "v-37a2960c",
    path: "/guide/7.%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%9E%B6%E6%9E%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37a2960c").then(next)
    },
  },
  {
    path: "/guide/7.微服务架构.html",
    redirect: "/guide/7.%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%9E%B6%E6%9E%84.html"
  },
  {
    path: "/guide/7.微服务架构.html",
    redirect: "/guide/7.%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%9E%B6%E6%9E%84.html"
  },
  {
    name: "v-74c11084",
    path: "/guide/8.nginx_jwt_maven_git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74c11084").then(next)
    },
  },
  {
    name: "v-23e3b6e3",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23e3b6e3").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-b2945578",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b2945578").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-42778a5a",
    path: "/plugin/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42778a5a").then(next)
    },
  },
  {
    path: "/plugin/index.html",
    redirect: "/plugin/"
  },
  {
    name: "v-06d5ee89",
    path: "/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-06d5ee89").then(next)
    },
  },
  {
    path: "/theme/index.html",
    redirect: "/theme/"
  },
  {
    name: "v-98461484",
    path: "/guide/assets.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-98461484").then(next)
    },
  },
  {
    name: "v-f9ff693c",
    path: "/theme/blog-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f9ff693c").then(next)
    },
  },
  {
    name: "v-679db604",
    path: "/guide/using-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-679db604").then(next)
    },
  },
  {
    name: "v-22794c7a",
    path: "/theme/default-theme-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-22794c7a").then(next)
    },
  },
  {
    name: "v-13316a99",
    path: "/notes/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13316a99").then(next)
    },
  },
  {
    path: "/notes/index.html",
    redirect: "/notes/"
  },
  {
    name: "v-78fd463e",
    path: "/theme/inheritance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-78fd463e").then(next)
    },
  },
  {
    name: "v-53c1c89a",
    path: "/theme/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-53c1c89a").then(next)
    },
  },
  {
    name: "v-ebf39c04",
    path: "/theme/writing-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ebf39c04").then(next)
    },
  },
  {
    name: "v-7b3adf04",
    path: "/theme/using-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b3adf04").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]