/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\oJavaOpen\\MyLog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-0ee2a348",
    path: "/api/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ee2a348").then(next)
    },
  },
  {
    name: "v-5e05fe2a",
    path: "/api/cli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e05fe2a").then(next)
    },
  },
  {
    name: "v-68eee3a8",
    path: "/guide/1.%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68eee3a8").then(next)
    },
  },
  {
    path: "/guide/1.数据结构.html",
    redirect: "/guide/1.%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html"
  },
  {
    path: "/guide/1.数据结构.html",
    redirect: "/guide/1.%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html"
  },
  {
    name: "v-77732336",
    path: "/guide/2.JAVA%E5%9F%BA%E7%A1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77732336").then(next)
    },
  },
  {
    path: "/guide/2.JAVA基础.html",
    redirect: "/guide/2.JAVA%E5%9F%BA%E7%A1%80.html"
  },
  {
    path: "/guide/2.JAVA基础.html",
    redirect: "/guide/2.JAVA%E5%9F%BA%E7%A1%80.html"
  },
  {
    name: "v-4ac501d2",
    path: "/guide/3.%20%E9%9B%86%E5%90%88%E9%9D%A2%E8%AF%95%E6%80%BB%E9%9B%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ac501d2").then(next)
    },
  },
  {
    path: "/guide/3. 集合面试总集.html",
    redirect: "/guide/3.%20%E9%9B%86%E5%90%88%E9%9D%A2%E8%AF%95%E6%80%BB%E9%9B%86.html"
  },
  {
    path: "/guide/3. 集合面试总集.html",
    redirect: "/guide/3.%20%E9%9B%86%E5%90%88%E9%9D%A2%E8%AF%95%E6%80%BB%E9%9B%86.html"
  },
  {
    name: "v-127d73e3",
    path: "/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-127d73e3").then(next)
    },
  },
  {
    path: "/faq/index.html",
    redirect: "/faq/"
  },
  {
    name: "v-3427c1b2",
    path: "/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3427c1b2").then(next)
    },
  },
  {
    path: "/config/index.html",
    redirect: "/config/"
  },
  {
    name: "v-249d0098",
    path: "/guide/5.%E5%A4%9A%E7%BA%BF%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-249d0098").then(next)
    },
  },
  {
    path: "/guide/5.多线程.html",
    redirect: "/guide/5.%E5%A4%9A%E7%BA%BF%E7%A8%8B.html"
  },
  {
    path: "/guide/5.多线程.html",
    redirect: "/guide/5.%E5%A4%9A%E7%BA%BF%E7%A8%8B.html"
  },
  {
    name: "v-6fcfe3ec",
    path: "/guide/6.Redis.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6fcfe3ec").then(next)
    },
  },
  {
    name: "v-3b836fec",
    path: "/guide/assets.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b836fec").then(next)
    },
  },
  {
    name: "v-6964376a",
    path: "/guide/4.MySQL.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6964376a").then(next)
    },
  },
  {
    name: "v-1980bd0a",
    path: "/guide/8.nginx_jwt_maven_git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1980bd0a").then(next)
    },
  },
  {
    name: "v-3cab6d50",
    path: "/guide/7.%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%9E%B6%E6%9E%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3cab6d50").then(next)
    },
  },
  {
    path: "/guide/7.微服务架构.html",
    redirect: "/guide/7.%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%9E%B6%E6%9E%84.html"
  },
  {
    path: "/guide/7.微服务架构.html",
    redirect: "/guide/7.%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%9E%B6%E6%9E%84.html"
  },
  {
    name: "v-37424b90",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37424b90").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-3ee856a8",
    path: "/guide/Java%E5%85%AB%E8%82%A1%E5%9F%BA%E7%A1%80%EF%BC%88%E5%85%A8%EF%BC%89.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3ee856a8").then(next)
    },
  },
  {
    path: "/guide/Java八股基础（全）.html",
    redirect: "/guide/Java%E5%85%AB%E8%82%A1%E5%9F%BA%E7%A1%80%EF%BC%88%E5%85%A8%EF%BC%89.html"
  },
  {
    path: "/guide/Java八股基础（全）.html",
    redirect: "/guide/Java%E5%85%AB%E8%82%A1%E5%9F%BA%E7%A1%80%EF%BC%88%E5%85%A8%EF%BC%89.html"
  },
  {
    name: "v-1f9edc17",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f9edc17").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-61268e4a",
    path: "/guide/using-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61268e4a").then(next)
    },
  },
  {
    name: "v-0eec8fcd",
    path: "/notes/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0eec8fcd").then(next)
    },
  },
  {
    path: "/notes/index.html",
    redirect: "/notes/"
  },
  {
    name: "v-029113bd",
    path: "/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-029113bd").then(next)
    },
  },
  {
    path: "/theme/index.html",
    redirect: "/theme/"
  },
  {
    name: "v-4f6a39f2",
    path: "/plugin/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f6a39f2").then(next)
    },
  },
  {
    path: "/plugin/index.html",
    redirect: "/plugin/"
  },
  {
    name: "v-5745298a",
    path: "/theme/inheritance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5745298a").then(next)
    },
  },
  {
    name: "v-fdfbe234",
    path: "/theme/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fdfbe234").then(next)
    },
  },
  {
    name: "v-7f791674",
    path: "/theme/default-theme-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f791674").then(next)
    },
  },
  {
    name: "v-9f7edca4",
    path: "/theme/blog-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9f7edca4").then(next)
    },
  },
  {
    name: "v-afa0246c",
    path: "/theme/using-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-afa0246c").then(next)
    },
  },
  {
    name: "v-37e7ed6c",
    path: "/theme/writing-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37e7ed6c").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]